Задача 1.

In [19]:
import numpy as np

# Создание вектора из 100 случайных чисел от 1 до 10(включительно)
arr = np.random.randint(1, 11, size=100)

# Подсчет процента элементов больше 7
greater_than_7 = np.mean(arr > 7) * 100
print(f"Процент элементов в векторе, больших 7: {greater_than_7}%")

Процент элементов в векторе, больших 7: 22.0%


Задача 2.

In [43]:
import numpy as np

# Опыт из предыдущей задачи 1000 раз
results = []
cycles = 1000

for _ in range(cycles):
    arr = np.random.randint(1, 11, size=100)
    percentage = np.mean(arr > 7) * 100
    results.append(percentage)

# Подсчет количества результатов, равных 20%
count_equal_to_20 = np.sum(np.array(results) == 20)
print(f"Часть результатов, равных 20%: {count_equal_to_20 / cycles}")

Часть результатов, равных 20%: 0.009


Задача 3.

In [44]:
import numpy as np

# Создание матрицы 10x10
matrix = np.tile(np.arange(1, 11), (10, 1))
print(matrix)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


Задача 4.

In [45]:
import numpy as np

# Создание матрицы 10x10
matrix = np.tile(np.arange(1, 11), (10, 1))

# Нахождение суммы элементов в каждом столбце
sums = np.sum(matrix, axis=0)
print(sums)

[ 10  20  30  40  50  60  70  80  90 100]
